name: rapidapi-mcp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - requests>=2.26.0
  - aiohttp>=3.8.1
  - python-dotenv>=0.19.0
  - pytest>=7.0.0
  - pip:
    - rapidapi-connect>=0.1.2